# Generated by Django 4.2.9 on 2024-02-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_amount',
            new_name='amount',
        ),
    ]
