# Generated by Django 4.2.9 on 2024-02-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_basket_status'),
        ('staff', '0002_rename_order_amount_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name_shopper',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.ManyToManyField(to='catalog.basket'),
        ),
    ]
