# Generated by Django 4.2.9 on 2024-02-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_basket_brand_remove_basket_number_and_more'),
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='cars',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.cars'),
        ),
    ]
