# Generated by Django 4.2.9 on 2024-02-29 09:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_garage_cars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garage',
            options={'verbose_name': 'Garage', 'verbose_name_plural': 'Garage'},
        ),
        migrations.AlterModelManagers(
            name='garage',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
