# Generated by Django 4.2.9 on 2024-02-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('O', 'Ordered'), ('D', 'Done')], default='P', max_length=1),
        ),
    ]
