# Generated by Django 4.2.9 on 2024-02-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_basket_price_alter_basket_shopper'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='brand',
            field=models.CharField(default='bmw', max_length=70),
        ),
    ]
