# Generated by Django 4.2.9 on 2024-03-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_cars_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='car',
            field=models.ManyToManyField(to='catalog.cars'),
        ),
    ]
