# Generated by Django 4.2.9 on 2024-03-01 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_component_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='car',
        ),
        migrations.AddField(
            model_name='component',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.cars'),
        ),
    ]
